Here I am removing the weird articls and checking if the publications are news partnerships.

In [282]:
#import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Publication data

In [405]:
#the origional data pub
pub_df = pd.read_csv(
    "hf://datasets/center-for-community-news/student-media-feeds/publication_corpora_manifest.csv"
)

pub_df.head()

,publication,slug,corpus_file,story_count,total_words,earliest_story,latest_story
0,The NewsHouse,the-newshouse,publication_corpora/the-newshouse.txt,381,265937,2026-02-05T05:00:00+00:00,"Wed, 29 Oct 2025 04:00:00 +0000"
1,The Observer,the-observer,publication_corpora/the-observer.txt,230,180917,2026-02-06T17:15:01+00:00,2026-06-21T01:05:07+00:00
2,The Daily Iowan,the-daily-iowan,publication_corpora/the-daily-iowan.txt,141,89601,2026-02-02T06:17:37Z,"Wed, 04 Feb 2026 15:20:28 +0000"
3,The Seattle Medium,the-seattle-medium,publication_corpora/the-seattle-medium.txt,130,108923,2026-03-18T14:30:00+00:00,"Wed, 04 Feb 2026 16:35:00 +0000"
4,Voice of OC,voice-of-oc,publication_corpora/voice-of-oc.txt,124,103923,2026-03-11T08:28:19+00:00,"Wed, 28 Jan 2026 21:25:53 +0000"

In [406]:
#drop earliest and latest story as well as total word count as they will not be used in our analysis
pub_df = pub_df.drop(['total_words','earliest_story','latest_story'],axis=1)

In [407]:
#This is the dataset after the institutions were added and the news partnership status was found
pub_corp = pd.read_csv("final_pub.csv")

In [408]:
pub_corp.head()

,source,slug,institution,news_partnership,story_count,corpus_file
0,The NewsHouse,the-newshouse,Syracuse University,0.0,381,publication_corpora/the-newshouse.txt
1,The Observer,the-observer,University of Illinois Springfield,0.0,10,publication_corpora/the-observer.txt
2,The Observer-NDSM,the-observer,"University of Notre Dame, Saint Mary's College...",0.0,46,publication_corpora/the-observer.txt
3,The Observer-FU,the-observer,Fordham University,0.0,98,publication_corpora/the-observer.txt
4,The Observer-CWU,the-observer,Central Washington University,0.0,10,publication_corpora/the-observer.txt

In [409]:
len(pub_corp)

929

In [410]:
sum(pub_corp['story_count'])

14712

In [411]:
#fix publications
pub_corp.loc[pub_corp['source'] == 'REAL NEWS BY REAL STUDENTS', 'source'] = 'Coyote Chronicle'
pub_corp.loc[pub_corp['source'] == 'www.komu.com - RSS Results of type article with keyword(s) of #topstory', 'source'] = 'KOMU 8'
pub_corp.loc[pub_corp['source'] == 'CU-CitizenAccess.org', 'source'] = 'CU-CitizenAccess'
pub_corp.loc[pub_corp['source'] == 'News Feed', 'source'] = 'WUFT'
pub_corp.loc[pub_corp['source'] == 'NewsLINC - Latest News', 'source'] = 'NewsLine'
pub_corp.loc[pub_corp['source'] == 'www.columbiamissourian.com - RSS Results of type article with keyword(s) of #topstory', 'source'] = 'The Columbia Missourian'
pub_corp.loc[pub_corp['source'] == 'www.thedaonline.com - RSS Results of type article', 'source'] = 'The Daily Athenaeum'
pub_corp.loc[pub_corp['source'] == 'www.dailygazette.com - RSS Results in spotlightnews of type article', 'source'] = 'The Daily Gazette'
pub_corp.loc[pub_corp['source'] == 'The Brown Daily Herald: Top Stories', 'source'] = 'The Brown Daily Herald'
pub_corp.loc[pub_corp['source'] == 'WKUHerald.com', 'source'] = 'College Heights Herald'
pub_corp.loc[pub_corp['source'] == 'www.dailycal.org - RSS Results', 'source'] = 'The Daily Californians'
pub_corp.loc[pub_corp['source'] == 'www.nebraskanewsservice.net - RSS Results', 'source'] = 'Nebraska News Service'
pub_corp.loc[pub_corp['source'] == 'www.easternprogress.com - RSS Results', 'source'] = 'The Eastern Progress'
pub_corp.loc[pub_corp['source'] == 'www.jackcentral.org - RSS Results of type article', 'source'] = 'The Lumberjack'
pub_corp.loc[pub_corp['source'] == 'www-westernherald-com-rss-results-of-type-article', 'source'] = 'Western Herald'
pub_corp.loc[pub_corp['source'] == 'www-cowleycollegemedia-com-rss-results-of-type-article', 'source'] = 'Cowley College Media'
pub_corp.loc[pub_corp['source'] == 'www-isustudentmedia-com-rss-results-in-indianastatesman-of-type-article', 'source'] = 'Indiana Statesman'
pub_corp.loc[pub_corp['source'] == 'liberty-alumnus-leads-security-efforts-in-fight-against-drugs-illegal-weapons-and-trafficking-in-caribbean-nation-liberty-news', 'source'] = 'Liberty News'
pub_corp.loc[pub_corp['source'] == 'mysite', 'source'] = 'The Valley Star News'
pub_corp.loc[pub_corp['source'] == 'Snow College news', 'source'] = 'Snowdrift'
pub_corp.loc[pub_corp['source'] == 'Student Senate Association, Inc.  PURCHASE PHOENIX', 'source'] = 'The Purchase Phoenix'
pub_corp.loc[pub_corp['source'] == 'My Site', 'source'] = 'The Commuter-NCA'
pub_corp.loc[pub_corp['source'] == 'AUM', 'source'] = 'Warhawk Weekly'
pub_corp.loc[pub_corp['source'] == 'All the Lehigh University News First - The Brown and White', 'source'] = 'The Brown and White'
pub_corp.loc[pub_corp['source'] == 'Belmont Abbey College', 'source'] = 'Abbey News'
pub_corp.loc[pub_corp['source'] == 'Coyote Student News at the College of Southern Nevada', 'source'] = 'Coyote Student News'
pub_corp.loc[pub_corp['source'] == 'Knightly News | Central Penn College’s Student News Organization', 'source'] = 'Knightly News'
pub_corp.loc[pub_corp['source'] == 'Mcccagora', 'source'] = 'Agora'
pub_corp.loc[pub_corp['source'] == 'Mesquite-News – Texas A&M University San Antonio', 'source'] = 'The Mesquite'
pub_corp.loc[pub_corp['source'] == 'Stories by Outlook Student Press RCC on Medium', 'source'] = 'Outlook Student Press'
pub_corp.loc[pub_corp['source'] == 'Prarie View A&M (pvpanther)', 'source'] = 'The Panther'
pub_corp.loc[pub_corp['source'] == 'The Cypress Chronicle – A First Amendment Publication in Cypress, California', 'source'] = 'The Cypress Chronicle'
pub_corp.loc[pub_corp['source'] == 'Threefold Advocate - JBU Student Newspaper', 'source'] = 'Threefold Advocate'
pub_corp.loc[pub_corp['source'] == 'dailytitan.com - RSS Results', 'source'] = 'Daily Titan'
pub_corp.loc[pub_corp['source'] =='Moraine Valley Community College', 'source'] = 'The Glacier'
pub_corp.loc[pub_corp['source'] == 'http://www.cccvoice.com/feed/', 'source'] = 'CCC The Voice'
pub_corp.loc[pub_corp['source'] == 'https://bonfire.digital.uic.edu/feed/', 'source'] = 'Bonfire'
pub_corp.loc[pub_corp['source'] == 'https://cuatower.com/feed/', 'source'] = 'The Tower'
pub_corp.loc[pub_corp['source'] == 'https://fulcrumnewspaper.wpcomstaging.com/feed/', 'source'] = 'The Fulcrum'
pub_corp.loc[pub_corp['source'] == 'https://lcctorch.com/feed/', 'source'] = 'LCC The Torch'
pub_corp.loc[pub_corp['source'] == 'https://rutgersobserver.wordpress.com/feed/', 'source'] = 'Rutgers Observer'
pub_corp.loc[pub_corp['source'] == 'https://setonianonline.com/feed/', 'source'] = 'Setonian'
pub_corp.loc[pub_corp['source'] == 'https://statementmga.wpcomstaging.com/feed/', 'source'] = 'The Statement MGU'
pub_corp.loc[pub_corp['source'] == 'https://stocktonargo.com/feed/', 'source'] = 'The Argo'
pub_corp.loc[pub_corp['source'] == 'https://supicket.com/feed/', 'source'] = 'The Picket'
pub_corp.loc[pub_corp['source'] == 'https://tartan.gordon.edu/feed/', 'source'] = 'The Tartan-Gordon'
pub_corp.loc[pub_corp['source'] == 'https://thecritograph.com/feed/', 'source'] = 'The Critograph'
pub_corp.loc[pub_corp['source'] == 'https://themetropolitan.metrostate.edu/feed/', 'source'] = 'The Metropolitan'
pub_corp.loc[pub_corp['source'] == 'https://theminaretonline.org/feed/', 'source'] = 'The Minaret'
pub_corp.loc[pub_corp['source'] == 'https://theredlandsbulldog.com/index.php/feed/', 'source'] = 'Redlands Bulldog'
pub_corp.loc[pub_corp['source'] == 'https://thesewaneepurple.org/feed/', 'source'] = 'The Sewanee'
pub_corp.loc[pub_corp['source'] == 'https://thestroudcourier.com/feed/', 'source'] = 'The Stroud Courier'
pub_corp.loc[pub_corp['source'] == 'https://thetowerlight.com/feed/', 'source'] = 'The Towerlight'
pub_corp.loc[pub_corp['source'] == 'https://thevalleyvanguard.com/feed/', 'source'] = 'The Valley Vanguard'
pub_corp.loc[pub_corp['source'] == 'https://troubonline.com/feed/', 'source'] = 'The Troubadour'
pub_corp.loc[pub_corp['source'] == 'https://www.fsuthevoice.com/feed/', 'source'] = 'FSU The Voice'
pub_corp.loc[pub_corp['source'] == 'https://www.marcolian.com/?feed=rss2', 'source'] = 'The Marcolina'
pub_corp.loc[pub_corp['source'] == 'https://www.rvcvalleyforge.com/index.php/feed/', 'source'] = 'The Valley Forge'
pub_corp.loc[pub_corp['source'] == 'https://www.thecbctower.com/feed/', 'source'] = 'The CBC  Tower'
pub_corp.loc[pub_corp['source'] == 'https://yorkpbnews.net/feed/', 'source'] = 'Pandoras Box'
pub_corp.loc[pub_corp['source'] == 'www.dailycal.org - RSS Results', 'source'] = 'The Daily Californian'
pub_corp.loc[pub_corp['source'] == 'www.ntdaily.com - RSS Results', 'source'] = 'North Texas Daily'
pub_corp.loc[pub_corp['source'] == 'www.uatrav.com - RSS Results', 'source'] = 'The Arkansas Traveler'
pub_corp.loc[pub_corp['source'] == 'www.videtteonline.com - RSS Results', 'source'] = 'The Vidette'
pub_corp.loc[pub_corp['source'] == 'https://www.ccclarion.com/feed/', 'source'] = 'CC Clarion'
pub_corp.loc[pub_corp['source'] == 'Home', 'source'] = 'The Daily Universe'
pub_corp.loc[pub_corp['source'] == 'uwrfvoice.com', 'source'] = 'Student Voice'

In [412]:
#Publications that were recorded under two seperate publications. We are assigning them the same name for future data cleaning.
pub_corp.loc[pub_corp['source'] =='https://kentstatenewslab.org/feed/', 'source'] = 'Kent State NewsLab'
pub_corp.loc[pub_corp['source'] =='News - F Newsmagazine', 'source'] = 'F Newsmagazine'
pub_corp.loc[pub_corp['source'] =='News - The Daily Illini', 'source'] = 'The Daily Illini'
pub_corp.loc[pub_corp['source'] =='News - F Newsmagazine', 'source'] = 'F Newsmagazine'
pub_corp.loc[pub_corp['source'] =='News - The Gettysburgian.', 'source'] = 'The Gettysburgian.'
pub_corp.loc[pub_corp['source'] =='News - Herd Media', 'source'] = 'Herd Media'
pub_corp.loc[pub_corp['source'] =='News – Daily Sundial', 'source'] = 'Daily Sundial'
pub_corp.loc[pub_corp['source'] =='News – The Crestiad', 'source'] = 'The Crestiad'
pub_corp.loc[pub_corp['source'] =='News - The Insight', 'source'] = 'The Insight'
pub_corp.loc[pub_corp['source'] =='Online Only – Richland Student Media', 'source'] = 'Richland Student Media'
pub_corp.loc[pub_corp['source'] =='News Archives - SXU Student Media', 'source'] = 'SXU Student Media'
pub_corp.loc[pub_corp['source'] =='The Sundial', 'source'] = 'The Suffolk Journal'
pub_corp.loc[pub_corp['source'] =='News – Viking Fusion', 'source'] = 'Viking Fusion'
pub_corp.loc[pub_corp['source'] =='News – Davidsonian', 'source'] = 'Davidsonian'
pub_corp.loc[pub_corp['source'] =='News – Lindenlink', 'source'] = 'Lindenlink'
pub_corp.loc[pub_corp['source'] =='News & Features – The Gleaner', 'source'] = 'The Gleaner'
pub_corp.loc[pub_corp['source'] =='News – The Tacoma Ledger', 'source'] = 'News – The Tacoma Ledger'
pub_corp.loc[pub_corp['source'] =='News – Luther College Chips', 'source'] = 'Luther College Chips'
pub_corp.loc[pub_corp['source'] =='News – Moraine Valley Community College', 'source'] = 'The Glacier'
pub_corp.loc[pub_corp['source'] =='News – GWU-Today', 'source'] = 'GWU-Today'
pub_corp.loc[pub_corp['source'] =='Comments on: Front Page', 'source'] = 'Almagest at LSUS'
pub_corp.loc[pub_corp['source'] =='Stories', 'source'] = 'The Critograph'

In [413]:
#check to see if it worked
pub_corp.loc[pub_corp['source']=='The Argo']

,source,slug,institution,news_partnership,story_count,corpus_file
514,The Argo,the-argo,Stockton University,0.0,10,publication_corpora/the-argo.txt
842,The Argo,https-stocktonargo-com-feed,Stockton University,0.0,10,publication_corpora/https-stocktonargo-com-fee...

In [414]:
pub_corp['source'].nunique()

908

### Story data

In [415]:
story_ind = story_df = pd.read_parquet(
    "hf://datasets/center-for-community-news/student-media-feeds/stories.parquet")

story_ind.head()

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,full_text_path,full_text
0,Point Park News Service,"At Gymsport Athletic Center, Adults Are Flippi...",https://pointparknewsservice.org/at-gymsport-a...,"Fri, 19 Dec 2025 19:19:34 +0000",2026-02-03 11:52:48,Competency | Sportsincollege | Elevating | Stu...,gymsport | athletic | center | adults | flipping,neutral,0.0,ok,,
1,Point Park News Service,Finding A Sense of Belonging in Pittsburgh Bal...,https://pointparknewsservice.org/finding-a-sen...,"Fri, 14 Nov 2025 22:33:44 +0000",2026-02-03 11:52:48,Unclassified,finding | sense | belonging | pittsburgh | ballet,neutral,0.0,ok,,
2,Point Park News Service,Scenes from Mayor Corey O’Connor’s victory party,https://pointparknewsservice.org/scenes-from-m...,"Wed, 05 Nov 2025 05:13:49 +0000",2026-02-03 11:52:48,Unclassified,scenes | mayor | corey | connor | victory,neutral,0.0,ok,,
3,Point Park News Service,Faces of the vote,https://pointparknewsservice.org/faces-of-the-...,"Wed, 05 Nov 2025 01:36:35 +0000",2026-02-03 11:52:48,Legislative | Legislation | Initiative | Gov |...,faces | vote,neutral,0.0,ok,,
4,Point Park News Service,Scenes from Election Day at The Sterrett Class...,https://pointparknewsservice.org/scenes-from-e...,"Wed, 05 Nov 2025 00:53:52 +0000",2026-02-03 11:52:48,Regal | Review | Hollywood | Cottages | Movies,scenes | election | sterrett | classical | aca...,neutral,0.0,ok,,

In [416]:
len(story_ind)

15074

#### Fix sources with multiple links

There are some source names that contain links to multiple colleges papers with the same name. To fix this we will be changing the source name so each college has a unique source.

In [417]:
#The Observer
story_ind.loc[7231:7276,'source'] = 'The Observer-NDSM'
story_ind.loc[9660:9757,'source'] = 'The Observer-FU'
story_ind.loc[10173:10182,'source'] = 'The Observer-CWU'
story_ind.loc[11759:11768,'source'] = 'The Observer-CWRU'
#Campus Times
story_ind.loc[13711:13810,'source'] = 'Campus Times-LV'
#The Echo
story_ind.loc[7735:7774,'source'] = 'The Echo News'
story_ind.loc[9989:10008,'source'] = 'The OC Echo'
story_ind.loc[11252:11261,'source'] = 'The Echo-PPSC'
story_ind.loc[12607:12626,'source'] = 'The Echo-SNU'
story_ind.loc[14643:14652,'source'] = 'The Echo-AU'
#The Collegian
story_ind.loc[6397:6406,'source'] = 'The Collegian-FS'
story_ind.loc[7061:7070,'source'] = 'The Collegian-SDSU'
story_ind.loc[8466:8475,'source'] = 'The Collegian-Delta'
story_ind.loc[11408:11417,'source'] = 'The Collegian-TU'
story_ind.loc[11468:11477,'source'] = 'The Collegian-BJ'
story_ind.loc[12026:12035,'source'] = 'The Collegian-GCC'
story_ind.loc[12375:12384,'source'] = 'The Collegian-AU'
#The Catalyst
story_ind.loc[12057:12062,'source'] = 'The Catalyst-NCFC'
story_ind.loc[13661:13670,'source'] = 'The Catalyst-OW'
#The Beacon
story_ind.loc[13398:13427,'source'] = 'The Beacon-MC'
story_ind.loc[14448:14457,'source'] = 'The Beacon-WP'
#The Clarion
story_ind.loc[2515:2524,'source'] = 'The Clarion-MATC'
story_ind.loc[4202:4211,'source'] = 'The Clarion-MATC'
story_ind.loc[10445:10875,'source'] = 'The Clarion-SCC'
#The Chimes
story_ind.loc[9092:9101,'source'] = 'The Chimes-CU'
#The Flyer
story_ind.loc[14067:14086,'source'] = 'The Flyer-SU'
#The Oracle
story_ind.loc[9010:9019,'source'] = 'The Oracle-TnT'
story_ind.loc[10752:10761,'source'] = 'The Oracle-USF'
story_ind.loc[11318:11327,'source'] = 'The Oracle-OR'
#The Sentinel
story_ind.loc[6377:6386,'source'] = 'The Sentinel-RU'
story_ind.loc[9527:9536,'source'] = 'The Sentinel-NIC'
story_ind.loc[14926:14935,'source'] = 'The Sentinel-John Jay'
#The Spectator
story_ind.loc[8631:8640,'source'] = 'The Spectator-CUc'
story_ind.loc[11675:11684,'source'] = 'The Spectator-SU'
story_ind.loc[13691:13700,'source'] = 'The Spectator-UWec'
#The Paw Print - the new name matches the other source name of the same publication
story_ind.loc[11891:11905,'source'] = 'ThePawPrint'
#The Buccaneer
story_ind.loc[9914:9933,'source'] = 'The Buccaneer-BU'
#The Forum
story_ind.loc[7281:7290,'source'] = 'The Forum-UAlr'
story_ind.loc[9684:9693,'source'] = 'The Forum-PVCC'
#The Horizon
story_ind.loc[12627:12636,'source'] = 'The Horizon-WCC'
story_ind.loc[14850:14859,'source'] = 'The Horizon-WC'
#The Summit
story_ind.loc[11297:11306,'source'] = 'The Summit-GC'
#The Torch
story_ind.loc[8800:8809,'source'] = 'The Torch-BCC'
story_ind.loc[9791:9800,'source'] = 'The Torch-St John'
#The Current
story_ind.loc[9179:9188,'source'] = 'The Current-UMsl'
story_ind.loc[9904:9913,'source'] = 'The Current-GRC'
#The Exponent
story_ind.loc[13103:13107,'source'] = 'The Exponent-NSU'
#The Pioneer
story_ind.loc[8556:8560,'source'] = 'The Pioneer-Cat'
story_ind.loc[14576:14585,'source'] = 'The Pioneer-CSUeb'
#The Reflector
story_ind.loc[9567:9581,'source'] = 'The Reflector-UI'
#The Record
story_ind.loc[7484,'source'] = 'The Record-GC'
story_ind.loc[13957:13966,'source'] = 'The Record-saints'
#Old Gold & Black
story_ind.loc[11458:11467,'source'] = 'Old Gold & Black-WFU'
#The Campus
story_ind.loc[13701:13710,'source'] = 'The Campus-CS'
#The Connector
story_ind.loc[8083:8092,'source'] = 'The Connector-UMassL'
#The Daily Campus
story_ind.loc[14103:14112,'source'] = 'The Daily Campus-Uconn'
#The Hawkeye
story_ind.loc[14279:14288,'source'] = 'The Hawkeye-ULm'
#The Leader
story_ind.loc[8780:8789,'source'] = 'The Leader-EU'
#The Patriot
story_ind.loc[9557:9566,'source'] = 'The Patriot-UC'
#The Point
story_ind.loc[12777:12786,'source'] = 'The Point-PLNU'
#The Prospector
story_ind.loc[14370:14379,'source'] = 'The Prospector-UTep'
#The Pulse
story_ind.loc[9547:9556,'source'] = 'The Pulse-UF'
#The Rambler
story_ind.loc[12787:12796,'source'] = 'The Rambler-TU'
#The Roar
story_ind.loc[6651:6660,'source'] = 'The Roar-PU'
#The Triangle
story_ind.loc[11101:11105,'source'] = 'The Triangle-BCd'
#The Voice
story_ind.loc[10691:10700,'source'] = 'The Voice-EOU'
#The Highlander
story_ind.loc[13904:13911,'source'] = 'The Highlander-Lyon'
#The Bulletin
story_ind.loc[9320:9324,'source'] = 'The Bulletin-CSUdh'
#The Columns
story_ind.loc[7898:7902,'source'] = 'The Columns-WC'
#blank source
story_ind.loc[974:983,'source'] = 'Kent State NewsLab'

#### Fix source names

There are some source names that are not the actual name of the paper. Many of these are links or names that were scraped incorrectly. There may be other sources that are not the exact name of the paper, but we only changed them if they were very wrong or long.

In [418]:
#fix publications
story_ind.loc[story_ind['source'] == 'REAL NEWS BY REAL STUDENTS', 'source'] = 'Coyote Chronicle'
story_ind.loc[story_ind['source'] == 'www.komu.com - RSS Results of type article with keyword(s) of #topstory', 'source'] = 'KOMU 8'
story_ind.loc[story_ind['source'] == 'CU-CitizenAccess.org', 'source'] = 'CU-CitizenAccess'
story_ind.loc[story_ind['source'] == 'News Feed', 'source'] = 'WUFT'
story_ind.loc[story_ind['source'] == 'NewsLINC - Latest News', 'source'] = 'NewsLine'
story_ind.loc[story_ind['source'] == 'www.columbiamissourian.com - RSS Results of type article with keyword(s) of #topstory', 'source'] = 'The Columbia Missourian'
story_ind.loc[story_ind['source'] == 'www.thedaonline.com - RSS Results of type article', 'source'] = 'The Daily Athenaeum'
story_ind.loc[story_ind['source'] == 'www.dailygazette.com - RSS Results in spotlightnews of type article', 'source'] = 'The Daily Gazette'
story_ind.loc[story_ind['source'] == 'The Brown Daily Herald: Top Stories', 'source'] = 'The Brown Daily Herald'
story_ind.loc[story_ind['source'] == 'WKUHerald.com', 'source'] = 'College Heights Herald'
story_ind.loc[story_ind['source'] == 'www.dailycal.org - RSS Results', 'source'] = 'The Daily Californians'
story_ind.loc[story_ind['source'] == 'www.nebraskanewsservice.net - RSS Results', 'source'] = 'Nebraska News Service'
story_ind.loc[story_ind['source'] == 'www.easternprogress.com - RSS Results', 'source'] = 'The Eastern Progress'
story_ind.loc[story_ind['source'] == 'www.jackcentral.org - RSS Results of type article', 'source'] = 'The Lumberjack'
story_ind.loc[story_ind['source'] == 'www-westernherald-com-rss-results-of-type-article', 'source'] = 'Western Herald'
story_ind.loc[story_ind['source'] == 'www-cowleycollegemedia-com-rss-results-of-type-article', 'source'] = 'Cowley College Media'
story_ind.loc[story_ind['source'] == 'www-isustudentmedia-com-rss-results-in-indianastatesman-of-type-article', 'source'] = 'Indiana Statesman'
story_ind.loc[story_ind['source'] == 'liberty-alumnus-leads-security-efforts-in-fight-against-drugs-illegal-weapons-and-trafficking-in-caribbean-nation-liberty-news', 'source'] = 'Liberty News'
story_ind.loc[story_ind['source'] == 'mysite', 'source'] = 'The Valley Star News'
story_ind.loc[story_ind['source'] == 'Snow College news', 'source'] = 'Snowdrift'
story_ind.loc[story_ind['source'] == 'Student Senate Association, Inc.  PURCHASE PHOENIX', 'source'] = 'The Purchase Phoenix'
story_ind.loc[story_ind['source'] == 'My Site', 'source'] = 'The Commuter-NCA'
story_ind.loc[story_ind['source'] == 'AUM', 'source'] = 'Warhawk Weekly'
story_ind.loc[story_ind['source'] == 'All the Lehigh University News First - The Brown and White', 'source'] = 'The Brown and White'
story_ind.loc[story_ind['source'] == 'Belmont Abbey College', 'source'] = 'Abbey News'
story_ind.loc[story_ind['source'] == 'Coyote Student News at the College of Southern Nevada', 'source'] = 'Coyote Student News'
story_ind.loc[story_ind['source'] == 'Knightly News | Central Penn College’s Student News Organization', 'source'] = 'Knightly News'
story_ind.loc[story_ind['source'] == 'Mcccagora', 'source'] = 'Agora'
story_ind.loc[story_ind['source'] == 'Mesquite-News – Texas A&M University San Antonio', 'source'] = 'The Mesquite'
story_ind.loc[story_ind['source'] == 'Stories by Outlook Student Press RCC on Medium', 'source'] = 'Outlook Student Press'
story_ind.loc[story_ind['source'] == 'Prarie View A&M (pvpanther)', 'source'] = 'The Panther'
story_ind.loc[story_ind['source'] == 'The Cypress Chronicle – A First Amendment Publication in Cypress, California', 'source'] = 'The Cypress Chronicle'
story_ind.loc[story_ind['source'] == 'Threefold Advocate - JBU Student Newspaper', 'source'] = 'Threefold Advocate'
story_ind.loc[story_ind['source'] == 'dailytitan.com - RSS Results', 'source'] = 'Daily Titan'
story_ind.loc[story_ind['source'] =='Moraine Valley Community College', 'source'] = 'The Glacier'
story_ind.loc[story_ind['source'] == 'http://www.cccvoice.com/feed/', 'source'] = 'CCC The Voice'
story_ind.loc[story_ind['source'] == 'https://bonfire.digital.uic.edu/feed/', 'source'] = 'Bonfire'
story_ind.loc[story_ind['source'] == 'https://cuatower.com/feed/', 'source'] = 'The Tower'
story_ind.loc[story_ind['source'] == 'https://fulcrumnewspaper.wpcomstaging.com/feed/', 'source'] = 'The Fulcrum'
story_ind.loc[story_ind['source'] == 'https://lcctorch.com/feed/', 'source'] = 'LCC The Torch'
story_ind.loc[story_ind['source'] == 'https://rutgersobserver.wordpress.com/feed/', 'source'] = 'Rutgers Observer'
story_ind.loc[story_ind['source'] == 'https://setonianonline.com/feed/', 'source'] = 'Setonian'
story_ind.loc[story_ind['source'] == 'https://statementmga.wpcomstaging.com/feed/', 'source'] = 'The Statement MGU'
story_ind.loc[story_ind['source'] == 'https://stocktonargo.com/feed/', 'source'] = 'The Argo'
story_ind.loc[story_ind['source'] == 'https://supicket.com/feed/', 'source'] = 'The Picket'
story_ind.loc[story_ind['source'] == 'https://tartan.gordon.edu/feed/', 'source'] = 'The Tartan-Gordon'
story_ind.loc[story_ind['source'] == 'https://thecritograph.com/feed/', 'source'] = 'The Critograph'
story_ind.loc[story_ind['source'] == 'https://themetropolitan.metrostate.edu/feed/', 'source'] = 'The Metropolitan'
story_ind.loc[story_ind['source'] == 'https://theminaretonline.org/feed/', 'source'] = 'The Minaret'
story_ind.loc[story_ind['source'] == 'https://theredlandsbulldog.com/index.php/feed/', 'source'] = 'Redlands Bulldog'
story_ind.loc[story_ind['source'] == 'https://thesewaneepurple.org/feed/', 'source'] = 'The Sewanee'
story_ind.loc[story_ind['source'] == 'https://thestroudcourier.com/feed/', 'source'] = 'The Stroud Courier'
story_ind.loc[story_ind['source'] == 'https://thetowerlight.com/feed/', 'source'] = 'The Towerlight'
story_ind.loc[story_ind['source'] == 'https://thevalleyvanguard.com/feed/', 'source'] = 'The Valley Vanguard'
story_ind.loc[story_ind['source'] == 'https://troubonline.com/feed/', 'source'] = 'The Troubadour'
story_ind.loc[story_ind['source'] == 'https://www.fsuthevoice.com/feed/', 'source'] = 'FSU The Voice'
story_ind.loc[story_ind['source'] == 'https://www.marcolian.com/?feed=rss2', 'source'] = 'The Marcolina'
story_ind.loc[story_ind['source'] == 'https://www.rvcvalleyforge.com/index.php/feed/', 'source'] = 'The Valley Forge'
story_ind.loc[story_ind['source'] == 'https://www.thecbctower.com/feed/', 'source'] = 'The CBC  Tower'
story_ind.loc[story_ind['source'] == 'https://yorkpbnews.net/feed/', 'source'] = 'Pandoras Box'
story_ind.loc[story_ind['source'] == 'www.dailycal.org - RSS Results', 'source'] = 'The Daily Californian'
story_ind.loc[story_ind['source'] == 'www.ntdaily.com - RSS Results', 'source'] = 'North Texas Daily'
story_ind.loc[story_ind['source'] == 'www.uatrav.com - RSS Results', 'source'] = 'The Arkansas Traveler'
story_ind.loc[story_ind['source'] == 'www.videtteonline.com - RSS Results', 'source'] = 'The Vidette'
story_ind.loc[story_ind['source'] == 'https://www.ccclarion.com/feed/', 'source'] = 'CC Clarion'
story_ind.loc[story_ind['source'] == 'Home', 'source'] = 'The Daily Universe'
story_ind.loc[story_ind['source'] == 'uwrfvoice.com', 'source'] = 'Student Voice'

In [419]:
#Publications that were recorded under two seperate publications. We are assigning them the same name for future data cleaning.
story_ind.loc[story_ind['source'] =='https://kentstatenewslab.org/feed/', 'source'] = 'Kent State NewsLab'
story_ind.loc[story_ind['source'] =='News - F Newsmagazine', 'source'] = 'F Newsmagazine'
story_ind.loc[story_ind['source'] =='News - The Daily Illini', 'source'] = 'The Daily Illini'
story_ind.loc[story_ind['source'] =='News - F Newsmagazine', 'source'] = 'F Newsmagazine'
story_ind.loc[story_ind['source'] =='News - The Gettysburgian.', 'source'] = 'The Gettysburgian.'
story_ind.loc[story_ind['source'] =='News - Herd Media', 'source'] = 'Herd Media'
story_ind.loc[story_ind['source'] =='News – Daily Sundial', 'source'] = 'Daily Sundial'
story_ind.loc[story_ind['source'] =='News – The Crestiad', 'source'] = 'The Crestiad'
story_ind.loc[story_ind['source'] =='News - The Insight', 'source'] = 'The Insight'
story_ind.loc[story_ind['source'] =='Online Only – Richland Student Media', 'source'] = 'Richland Student Media'
story_ind.loc[story_ind['source'] =='News Archives - SXU Student Media', 'source'] = 'SXU Student Media'
story_ind.loc[story_ind['source'] =='The Sundial', 'source'] = 'The Suffolk Journal'
story_ind.loc[story_ind['source'] =='News – Viking Fusion', 'source'] = 'Viking Fusion'
story_ind.loc[story_ind['source'] =='News – Davidsonian', 'source'] = 'Davidsonian'
story_ind.loc[story_ind['source'] =='News – Lindenlink', 'source'] = 'Lindenlink'
story_ind.loc[story_ind['source'] =='News & Features – The Gleaner', 'source'] = 'The Gleaner'
story_ind.loc[story_ind['source'] =='News – The Tacoma Ledger', 'source'] = 'News – The Tacoma Ledger'
story_ind.loc[story_ind['source'] =='News – Luther College Chips', 'source'] = 'Luther College Chips'
story_ind.loc[story_ind['source'] =='News – Moraine Valley Community College', 'source'] = 'The Glacier'
story_ind.loc[story_ind['source'] =='News – GWU-Today', 'source'] = 'GWU-Today'
story_ind.loc[story_ind['source'] =='Comments on: Front Page', 'source'] = 'Almagest at LSUS'
story_ind.loc[story_ind['source'] =='Stories', 'source'] = 'The Critograph'

In [420]:
story_ind['source'].nunique()

885

In [421]:
#no duplicates
len(story_ind.drop_duplicates(ignore_index=True))

15074

#### Add big college dataset - Schools & News Outlets 2026 from the CCN

In [422]:
school_and_news = pd.read_csv("Schools & News Outlets.csv")
school_and_news.head()

,UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,DFRCUSCG,INSTSIZE2,CBSATYPE2,CountyFIPS,FT_Enroll,Enrollment,Endowment,NewsPartnership,NewsOutlets2023,AdjCountyMin
0,102580,Alaska Bible College,,248 E Elmwood Ave,Palmer,AK,99645,2,8,David Ley,...,2,Very Small,Urban - Metro,02170,28.0,40.0,111585.0,NaN,2.0,0.0
1,103501,Alaska Career College,,1415 E Tudor Road,Anchorage,AK,99507-1033,2,8,Jennifer A. Deitz,...,2,Very Small,Urban - Metro,02020,412.0,412.0,NaN,NaN,7.0,1.0
2,442523,Alaska Christian College,,35109 Royal Place,Soldotna,AK,99669,2,8,Dr. Keith J. Hamilton,...,2,Very Small,Rural,02122,85.0,93.0,NaN,NaN,4.0,1.0
3,102669,Alaska Pacific University,,4101 University Dr,Anchorage,AK,99508,2,8,Dr. Janelle Vanasse,...,1,Very Small,Urban - Metro,02020,293.0,493.0,95533737.0,NaN,7.0,1.0
4,102711,Alaska Vocational Technical Center,AVTEC,PO Box 889,Seward,AK,99664-0889,2,8,Cathy LeCompte,...,2,Very Small,Rural,02122,60.0,185.0,NaN,NaN,4.0,1.0

In [423]:
school_and_news = school_and_news.rename(columns={'INSTNM':'institution'})

In [424]:
school_and_news = school_and_news[['institution','CITY','NewsOutlets2023','AdjCountyMin']]
school_and_news.head()

,institution,CITY,NewsOutlets2023,AdjCountyMin
0,Alaska Bible College,Palmer,2.0,0.0
1,Alaska Career College,Anchorage,7.0,1.0
2,Alaska Christian College,Soldotna,4.0,1.0
3,Alaska Pacific University,Anchorage,7.0,1.0
4,Alaska Vocational Technical Center,Seward,4.0,1.0

In [425]:
len(school_and_news)

6347

## combining the datasets

In [426]:
#combine the pub df with school_and_news
full_pub_df = pd.merge(pub_corp, school_and_news, how="left", on='institution')

In [427]:
full_pub_df.head()

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
0,The NewsHouse,the-newshouse,Syracuse University,0.0,381,publication_corpora/the-newshouse.txt,Syracuse,6.0,1.0
1,The Observer,the-observer,University of Illinois Springfield,0.0,10,publication_corpora/the-observer.txt,Springfield,12.0,1.0
2,The Observer-NDSM,the-observer,"University of Notre Dame, Saint Mary's College...",0.0,46,publication_corpora/the-observer.txt,NaN,NaN,NaN
3,The Observer-FU,the-observer,Fordham University,0.0,98,publication_corpora/the-observer.txt,Bronx,5.0,5.0
4,The Observer-CWU,the-observer,Central Washington University,0.0,10,publication_corpora/the-observer.txt,Ellensburg,2.0,1.0

In [428]:
full_pub_df = full_pub_df.drop_duplicates(ignore_index=True)

In [429]:
len(full_pub_df)

944

Some of the institutions share names with others in the Schools 2023 dataset. The correct institution needs to be selected.

In [430]:
#for each unique pub
for pub in pub_corp['source'].unique():
    #find count for full_df and story_ind
    full_count = len(full_pub_df[full_pub_df['source']== pub])
    pub_count = len(pub_corp[pub_corp['source']== pub])
    #if !=
    if full_count != pub_count:
        #print the source name
        print(pub)
    else:
        pass

The Clarion
TommieMedia
The Columns-WC
El Vaquero
Concordiensis
Emmanuel College The Hub
Myclarionnews.com
SWC The Sun Newspaper
The Andersonian
The Century Times

In [431]:
full_pub_df.loc[full_pub_df['source']=='The Clarion']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
71,The Clarion,the-clarion,Bethel University,0.0,10,publication_corpora/the-clarion.txt,Mishawaka,1.0,1.0
72,The Clarion,the-clarion,Bethel University,0.0,10,publication_corpora/the-clarion.txt,Saint Paul,7.0,3.0
73,The Clarion,the-clarion,Bethel University,0.0,10,publication_corpora/the-clarion.txt,McKenzie,2.0,1.0

In [432]:
#the correct university is in Saint Paul
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'The Clarion')&(full_pub_df['CITY'] != 'Saint Paul')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [433]:
full_pub_df.loc[full_pub_df['source']=='TommieMedia']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
259,TommieMedia,tommiemedia,University of St Thomas,0.0,20,publication_corpora/tommiemedia.txt,Saint Paul,7.0,3.0
260,TommieMedia,tommiemedia,University of St Thomas,0.0,20,publication_corpora/tommiemedia.txt,Houston,33.0,1.0

In [434]:
#the correct university is in Saint Paul
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'TommieMedia')&(full_pub_df['CITY'] != 'Saint Paul')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [435]:
full_pub_df.loc[full_pub_df['source']=='The Columns-WC']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
286,The Columns-WC,the-columns,Westminster College,0.0,5,publication_corpora/the-columns.txt,Fulton,1.0,1.0
287,The Columns-WC,the-columns,Westminster College,0.0,5,publication_corpora/the-columns.txt,New Wilmington,2.0,1.0
288,The Columns-WC,the-columns,Westminster College,0.0,5,publication_corpora/the-columns.txt,Salt Lake City,10.0,1.0

In [436]:
#the correct university is in Fulton
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'The Columns-WC')&(full_pub_df['CITY'] != 'Fulton')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [437]:
full_pub_df.loc[full_pub_df['source']=='El Vaquero']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
308,El Vaquero,el-vaquero,Glendale Community College,0.0,12,publication_corpora/el-vaquero.txt,Glendale,35.0,1.0
309,El Vaquero,el-vaquero,Glendale Community College,0.0,12,publication_corpora/el-vaquero.txt,Glendale,104.0,9.0

In [438]:
#the correct university has 104 news outlets
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'El Vaquero')&(full_pub_df['NewsOutlets2023'] != 104)),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [439]:
full_pub_df.loc[full_pub_df['source']=='Concordiensis']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
365,Concordiensis,concordiensis,Union College,0.0,10,publication_corpora/concordiensis.txt,Barbourville,1.0,1.0
366,Concordiensis,concordiensis,Union College,0.0,10,publication_corpora/concordiensis.txt,Lincoln,3.0,1.0
367,Concordiensis,concordiensis,Union College,0.0,10,publication_corpora/concordiensis.txt,Schenectady,1.0,1.0

In [440]:
#the correct university is in Schenectady
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'Concordiensis')&(full_pub_df['CITY'] != 'Schenectady')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [441]:
full_pub_df.loc[full_pub_df['source']=='Emmanuel College The Hub']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
389,Emmanuel College The Hub,emmanuel-college-the-hub,Emmanuel College,0.0,10,publication_corpora/emmanuel-college-the-hub.txt,Franklin Springs,1.0,0.0
390,Emmanuel College The Hub,emmanuel-college-the-hub,Emmanuel College,0.0,10,publication_corpora/emmanuel-college-the-hub.txt,Boston,22.0,10.0

In [442]:
#the correct university is in Boston
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'Emmanuel College The Hub')&(full_pub_df['CITY'] != 'Boston')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [443]:
full_pub_df.loc[full_pub_df['source']=='Myclarionnews.com']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
437,Myclarionnews.com,myclarionnews-com,Lincoln University,0.0,10,publication_corpora/myclarionnews-com.txt,Oakland,25.0,5.0
438,Myclarionnews.com,myclarionnews-com,Lincoln University,0.0,10,publication_corpora/myclarionnews-com.txt,Jefferson City,1.0,1.0
439,Myclarionnews.com,myclarionnews-com,Lincoln University,0.0,10,publication_corpora/myclarionnews-com.txt,Lincoln University,4.0,1.0

In [444]:
#the correct university is in Lincoln University
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'Myclarionnews.com')&(full_pub_df['CITY'] != 'Lincoln University')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [445]:
full_pub_df.loc[full_pub_df['source']=='SWC The Sun Newspaper']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
483,SWC The Sun Newspaper,swc-the-sun-newspaper,Southwestern College,0.0,10,publication_corpora/swc-the-sun-newspaper.txt,Chula Vista,38.0,9.0
484,SWC The Sun Newspaper,swc-the-sun-newspaper,Southwestern College,0.0,10,publication_corpora/swc-the-sun-newspaper.txt,Winfield,1.0,0.0
485,SWC The Sun Newspaper,swc-the-sun-newspaper,Southwestern College,0.0,10,publication_corpora/swc-the-sun-newspaper.txt,Santa Fe,4.0,0.0

In [446]:
#the correct university is in Chula Vista
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'SWC The Sun Newspaper')&(full_pub_df['CITY'] != 'Chula Vista')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [447]:
full_pub_df.loc[full_pub_df['source']=='The Andersonian']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
523,The Andersonian,the-andersonian,Anderson University,0.0,10,publication_corpora/the-andersonian.txt,Anderson,4.0,1.0
524,The Andersonian,the-andersonian,Anderson University,0.0,10,publication_corpora/the-andersonian.txt,Anderson,3.0,1.0

In [448]:
#the correct university has 4 outlets
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'The Andersonian')&(full_pub_df['NewsOutlets2023'] != 4)),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [449]:
full_pub_df.loc[full_pub_df['source']=='The Century Times']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
561,The Century Times,the-century-times,Century College,0.0,10,publication_corpora/the-century-times.txt,White Bear Lake,5.0,1.0
562,The Century Times,the-century-times,Century College,0.0,10,publication_corpora/the-century-times.txt,San Juan,NaN,NaN

In [450]:
#the correct university is in White Bear Lake
to_drop = full_pub_df.loc[((full_pub_df['source'] == 'The Century Times')&(full_pub_df['CITY'] != 'White Bear Lake')),:]
full_pub_df = full_pub_df.drop(to_drop.index)

In [451]:
#Run again to confirm it worked
for pub in pub_corp['source'].unique():
    #find count for full_df and story_ind
    full_count = len(full_pub_df[full_pub_df['source']== pub])
    pub_count = len(pub_corp[pub_corp['source']== pub])
    #if !=
    if full_count != pub_count:
        #print the source name
        print(pub)
    else:
        pass

In [452]:
len(full_pub_df)

929

There are publications that had the same name but different slugs that need to be combined.

In [453]:
#print out and save the source is the count > 1
double_pub_list = []
for i in range(len(full_pub_df['source'].value_counts())):
    if full_pub_df['source'].value_counts().to_list()[i] > 1:
        double_pub_list.append(full_pub_df['source'].value_counts().index.to_list()[i])
        print(full_pub_df['source'].value_counts().index.to_list()[i])

Richland Student Media
Lindenlink
The Crestiad
F Newsmagazine
The Glacier
Luther College Chips
The Daily Illini
The Lumberjack
The Argo
SXU Student Media
Daily Sundial
The Suffolk Journal
GWU-Today
Davidsonian
The Gleaner
The Critograph
Herd Media
Almagest at LSUS
Viking Fusion
Kent State NewsLab

In [454]:
#for each of the above publications, we will sum up the story count and drop one of them
for pub in double_pub_list:
    story_count = sum(full_pub_df[full_pub_df['source']==pub]['story_count'])
    full_pub_df.loc[full_pub_df['source']==pub,'story_count'] = story_count

In [455]:
full_pub_df[full_pub_df['source']=='Kent State NewsLab']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
328,Kent State NewsLab,https-kentstatenewslab-org-feed,Kent State University,1.0,21,publication_corpora/https-kentstatenewslab-org...,NaN,NaN,NaN
875,Kent State NewsLab,NaN,Kent State University,1.0,21,publication_corpora/nan.txt,NaN,NaN,NaN

In [456]:
#drop the duplicate publications
full_pub_df = full_pub_df.drop_duplicates(subset='source', keep="first")

In [457]:
full_pub_df[full_pub_df['source']=='Kent State NewsLab']

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
328,Kent State NewsLab,https-kentstatenewslab-org-feed,Kent State University,1.0,21,publication_corpora/https-kentstatenewslab-org...,NaN,NaN,NaN

In [458]:
len(full_pub_df)

909

#### Combine publication and story dataframes

In [459]:
#combine the above df with school_and_news
full_story_df = pd.merge(story_ind, full_pub_df, how="left", on='source')
full_story_df.head()

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,full_text_path,full_text,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
0,Point Park News Service,"At Gymsport Athletic Center, Adults Are Flippi...",https://pointparknewsservice.org/at-gymsport-a...,"Fri, 19 Dec 2025 19:19:34 +0000",2026-02-03 11:52:48,Competency | Sportsincollege | Elevating | Stu...,gymsport | athletic | center | adults | flipping,neutral,0.0,ok,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Point Park News Service,Finding A Sense of Belonging in Pittsburgh Bal...,https://pointparknewsservice.org/finding-a-sen...,"Fri, 14 Nov 2025 22:33:44 +0000",2026-02-03 11:52:48,Unclassified,finding | sense | belonging | pittsburgh | ballet,neutral,0.0,ok,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Point Park News Service,Scenes from Mayor Corey O’Connor’s victory party,https://pointparknewsservice.org/scenes-from-m...,"Wed, 05 Nov 2025 05:13:49 +0000",2026-02-03 11:52:48,Unclassified,scenes | mayor | corey | connor | victory,neutral,0.0,ok,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Point Park News Service,Faces of the vote,https://pointparknewsservice.org/faces-of-the-...,"Wed, 05 Nov 2025 01:36:35 +0000",2026-02-03 11:52:48,Legislative | Legislation | Initiative | Gov |...,faces | vote,neutral,0.0,ok,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Point Park News Service,Scenes from Election Day at The Sterrett Class...,https://pointparknewsservice.org/scenes-from-e...,"Wed, 05 Nov 2025 00:53:52 +0000",2026-02-03 11:52:48,Regal | Review | Hollywood | Cottages | Movies,scenes | election | sterrett | classical | aca...,neutral,0.0,ok,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [460]:
full_story_df[100:110]

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,full_text_path,full_text,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
100,Legislative Reporting Project,Student parents may lose financial support und...,https://reportformn.umn.edu/student-parents-ma...,"Fri, 02 May 2025 21:27:23 +0000",2026-02-03 11:52:48,Unclassified,student | parents | lose | financial | support,positive,0.1,ok,full_text/f2/f2f64e06cf494086e0f11dd6938dfefc4...,Published on 2025-05-02 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
101,Legislative Reporting Project,MN lawmakers look to more than double annual f...,https://reportformn.umn.edu/mn-lawmakers-look-...,"Fri, 02 May 2025 21:15:22 +0000",2026-02-03 11:52:48,Lawmakers | Capitol | Enrollments | Mn | Funding,lawmakers | look | double | annual | paid,neutral,0.0,ok,full_text/b0/b0e7a1e613512ef6d15c2b387131269a9...,Published on 2025-05-02 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
102,Legislative Reporting Project,MN Legislature debates response to bird flu ep...,https://reportformn.umn.edu/mn-legislature-deb...,"Fri, 02 May 2025 21:06:20 +0000",2026-02-03 11:52:48,Unclassified,legislature | debates | response | bird | epid...,neutral,0.0,ok,full_text/07/076a6f233742cc584dd7435c63978178e...,Published on 2025-05-02 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
103,Legislative Reporting Project,"Public safety bill increases funding, but some...",https://reportformn.umn.edu/public-safety-bill...,"Fri, 25 Apr 2025 20:44:13 +0000",2026-02-03 11:52:48,Lawmakers | Capitol | Enrollments | Mn | Funding,public | safety | bill | increases | funding,neutral,0.0,ok,full_text/34/343c713575d552601a43b7986e9d5831c...,Published on 2025-04-25 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
104,Legislative Reporting Project,Housing bill that includes down payment help p...,https://reportformn.umn.edu/housing-bill-inclu...,"Fri, 25 Apr 2025 20:33:16 +0000",2026-02-03 11:52:48,Lawmakers | Capitol | Enrollments | Mn | Funding,housing | bill | includes | down | payment,neutral,0.0,ok,full_text/88/88c9367ad8146d25edf4dd0b684827c7e...,Published on 2025-04-25 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
105,Legislative Reporting Project,"House funds U of M seed bank, but doubts raise...",https://reportformn.umn.edu/house-funds-u-m-se...,"Fri, 25 Apr 2025 16:37:24 +0000",2026-02-03 11:52:48,Unclassified,house | funds | seed | bank | doubts,neutral,0.0,ok,full_text/6c/6cbe441c4fe3c7ea1276e872024a08b02...,Published on 2025-04-25 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
106,Legislative Reporting Project,Funding for ‘crisis pregnancy centers’ and mat...,https://reportformn.umn.edu/funding-crisis-pre...,"Fri, 18 Apr 2025 21:23:35 +0000",2026-02-03 11:52:48,Lawmakers | Capitol | Enrollments | Mn | Funding,funding | crisis | pregnancy | centers | mater...,negative,-0.0714,ok,full_text/e9/e913ec2158168cba57e2bd61c805f941e...,Published on 2025-04-18 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
107,Legislative Reporting Project,Minnesota bill aims to criminalize AI-generate...,https://reportformn.umn.edu/minnesota-bill-aim...,"Fri, 18 Apr 2025 17:36:14 +0000",2026-02-03 11:52:48,Unclassified,minnesota | bill | aims | criminalize | ai-gen...,negative,-0.1111,ok,full_text/61/611d9fc0d6f843474f747092c18da54d0...,Published on 2025-04-18 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
108,Legislative Reporting Project,"Amid some grumbling, MN House committee approv...",https://reportformn.umn.edu/amid-some-grumblin...,"Fri, 18 Apr 2025 16:24:16 +0000",2026-02-03 11:52:48,Unclassified,amid | some | grumbling | house | committee,neutral,0.0,ok,full_text/b3/b3e61195f0da895ed42548123c607932f...,Published on 2025-04-18 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0
109,Legislative Reporting Project,Funding for ‘crisis pregnancy centers’ and mat...,https://reportformn.umn.edu/funding-crisis-pre...,"Fri, 18 Apr 2025 16:13:57 +0000",2026-02-03 11:52:48,Lawmakers | Capitol | Enrollments | Mn | Funding,funding | crisis | pregnancy | centers | mater...,negative,-0.0714,ok,full_text/5f/5f25a4c1d7d867b682dee9f75c8207e21...,Published on 2025-04-18 by Report for Minnesot...,legislative-reporting-project,University of Minnesota-Twin Cities,1.0,40.0,publication_corpora/legislative-reporting-proj...,Minneapolis,22.0,2.0

Some of the sources in the story dataframe were not in the list of publications. This is because there were issues with the webscraper and the text was blank. More explination can be seen at https://huggingface.co/center-for-community-news?message=You+successfully+joined+organization+center-for-community-news

In [461]:
full_story_df[full_story_df['institution'].isna()]['source'].unique()

array(['Point Park News Service', 'CommunityWire.Miami',
       'New York City News Service', '', 'The Arrow Latest News',
       'QCity Metro Latest News', 'The Beacon Today',
       'Page not found – The Rattler Online', 'The Southeastern',
       'The Wayne Stater', 'The Mossy Log', 'The Bison'], dtype=object)

In [462]:
#dropping the above sources
full_story_df = full_story_df.drop(full_story_df[full_story_df['institution'].isna()].index)

In [463]:
len(full_story_df)

14880

Some additional issues were discovered while finding the institution. These publications (seen below) were assigned DROP to their institution. More information on why they were droped can be found in the origional publication spredsheet.

In [464]:
full_story_df[full_story_df['institution']=='DROP']

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,full_text_path,full_text,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin
301,Voice of OC,Surf City Leaders Square Off With Friends of T...,https://voiceofoc.org/2026/02/city-council-lib...,"Tue, 03 Feb 2026 13:58:00 +0000",2026-02-03 11:52:48,Unclassified,surf | city | leaders | square | friends,neutral,0.0,ok,full_text/e3/e3c55757b5646fec97000580c3f10e2be...,Friends of the Library is a staple of voluntee...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
302,Voice of OC,Orange County Healthcare Workers Strike For Se...,https://voiceofoc.org/2026/02/orange-county-he...,"Mon, 02 Feb 2026 21:02:17 +0000",2026-02-03 11:52:48,Unclassified,orange | county | healthcare | workers | strike,negative,-0.125,ok,full_text/23/23e830fdefc57ba9f3b58e2e33bfcdac6...,"Over 30,000 healthcare workers who went on str...",voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
303,Voice of OC,Is Anaheim’s Controversial City Manager Callin...,https://voiceofoc.org/2026/02/is-anaheims-cont...,"Mon, 02 Feb 2026 19:00:15 +0000",2026-02-03 11:52:48,Immigration | Vote | Appoints | Government | R...,anaheim | controversial | city | manager | cal...,neutral,0.0,ok,full_text/27/2744a15b149ae19227158b7e4efe264ab...,Anaheim City Manager Jim Vanderpool has collec...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
304,Voice of OC,Laguna Beach Preserves Artist Housing Through ...,https://voiceofoc.org/2026/02/laguna-beach-pre...,"Mon, 02 Feb 2026 18:00:00 +0000",2026-02-03 11:52:48,Eviction | Tenants | Zoning | Council | Residents,laguna | beach | preserves | artist | housing,neutral,0.0,ok,full_text/97/97ef6af4bbe7643c3d1701c7da312aa29...,Artists in Laguna Beach will keep some afforda...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
305,Voice of OC,"Irvine Cracks Down on Reckless E-bike Riding, ...",https://voiceofoc.org/2026/02/irvine-cracks-do...,"Mon, 02 Feb 2026 13:58:00 +0000",2026-02-03 11:52:48,Unclassified,irvine | cracks | down | reckless | e-bike,neutral,0.0,ok,full_text/3c/3c349379adf1fe06b5f393500d78b11bf...,Irvine is slated to join a growing list of Ora...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14264,Voice of OC,All Orange County Residents Can Soon Call Into...,https://voiceofoc.org/2026/06/all-orange-count...,2026-06-23T12:58:00+00:00,2026-06-26T17:23:11.802759+00:00,Unclassified,orange | county | residents | city | council,neutral,0.0,ok,full_text/7d/7d5966a089ceb5db672b397dcd506862d...,All Orange County residents will be able to sp...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
14265,Voice of OC,Santana: Politician Spending Accounts Fuel Ban...,https://voiceofoc.org/2026/06/santana-politici...,2026-06-22T21:49:40+00:00,2026-06-26T17:23:11.802759+00:00,Unclassified,spending | accounts | santana | politician | fuel,neutral,0.0,ok,full_text/e9/e94c565aeb815ca3e70f7c14320f06022...,"Bloated office budgets, politicized staffers a...",voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
14266,Voice of OC,Voice of OC Wins Three First Place Awards at O...,https://voiceofoc.org/2026/06/voice-of-oc-wins...,2026-06-22T21:31:37+00:00,2026-06-26T17:23:11.802759+00:00,Conference | Andersonian | Academic | Alumnare...,voice | press | orange | wins | three,neutral,0.0161,ok,full_text/db/db9cf5ade8e1a405569c890590710f80e...,From ICE Raids in Orange County to Angels Stad...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
14267,Voice of OC,Could Orange County’s Landfill Expansion Threa...,https://voiceofoc.org/2026/06/could-orange-cou...,2026-06-22T20:00:00+00:00,2026-06-26T17:23:11.802759+00:00,Universities | Graduate | Schools | Retired | ...,orange | county | could | landfill | mountain,neutral,0.0,ok,full_text/a9/a9fe2806096bdf5f5b2c9092436d4d1a0...,One of the largest conservation groups in the ...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN
14268,Voice of OC,Santana: OC’s Treasurer/Tax Collector Protests...,https://voiceofoc.org/2026/06/santana-ocs-trea...,2026-06-22T12:58:00+00:00,2026-06-26T17:23:11.802759+00:00,Albany | Faculty | Pbs | Mhcc | Complaints,county | budget | santana | treasurer | collector,neutral,0.0,ok,full_text/1c/1c352bbd49840b948c661552d18b6f134...,While more than two thirds of Orange County vo...,voice-of-oc,DROP,NaN,124.0,publication_corpora/voice-of-oc.txt,NaN,NaN,NaN

In [465]:
#dropping the above sources
full_story_df = full_story_df.drop(full_story_df[full_story_df['institution']=='DROP'].index)

In [466]:
len(full_story_df)

14234

In [467]:
full_story_df['source'].nunique()

853

In [468]:
#dropping the above sources
full_pub_df = full_pub_df.drop(full_pub_df[full_pub_df['institution']=='DROP'].index)

In [469]:
len(full_pub_df)

888

### Drop all articles under 150 words

In [470]:
#create a word count
word_count = []
for i, row in full_story_df.iterrows():
    word_count.append(len(full_story_df.loc[i,"full_text"].split()))
full_story_df["word_count"] = word_count

In [471]:
full_story_df.tail()

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,...,full_text,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin,word_count
15069,The State News,Australian university student reps MSU across ...,https://statenews.com/article/2026/06/australi...,2026-06-23,2026-06-26T17:44:50.866505+00:00,Boca | Semester | Uc | Campaigning | Meeting,australian | university | student | reps | across,neutral,0.0,ok,...,"At Michigan State University, they tell you th...",the-state-news,Michigan State University,0.0,105.0,publication_corpora/the-state-news.txt,East Lansing,7.0,2.0,783
15070,The State News,East Lansing group collecting signatures to re...,https://statenews.com/article/2026/06/east-lan...,2026-06-22,2026-06-26T17:44:50.866505+00:00,Unclassified,east | lansing | group | collecting | signatures,neutral,0.0,ok,...,A local citizens group called Let East Lansing...,the-state-news,Michigan State University,0.0,105.0,publication_corpora/the-state-news.txt,East Lansing,7.0,2.0,800
15071,The Dartmouth,Dartmouth Divest for Palestine submits second ...,https://www.thedartmouth.com/article/2026/06/w...,2026-06-23,2026-06-26T17:48:47.210140+00:00,Speeches | Lecture | Healthcare | Student | Sp...,dartmouth | divest | palestine | submits | second,neutral,0.0,ok,...,"On June 22, Dartmouth Divest for Palestine sub...",the-dartmouth,Dartmouth College,0.0,101.0,publication_corpora/the-dartmouth.txt,Hanover,3.0,0.0,2418
15072,The Daily Nebraskan,"Best Aquamarine Jewelry That Feels Light, Luxu...",https://www.dailynebraskan.com/sponsoredconten...,,2026-06-26T17:50:08.708836+00:00,Unclassified,best | aquamarine | jewelry | feels | light,neutral,0.0,ok,...,"Jewelry trends change often, but some gemstone...",the-daily-nebraskan,University of Nebraska-Lincoln,0.0,4.0,publication_corpora/the-daily-nebraskan.txt,Lincoln,3.0,1.0,710
15073,The Daily Nebraskan,UNL College of Education and Human Sciences de...,https://www.dailynebraskan.com/news/administra...,,2026-06-26T17:50:08.708836+00:00,Faculty | College | Provosts | Ofthecollege | ...,college | education | human | sciences | dean,neutral,0.0,ok,...,The College of Education and Human Sciences de...,the-daily-nebraskan,University of Nebraska-Lincoln,0.0,4.0,publication_corpora/the-daily-nebraskan.txt,Lincoln,3.0,1.0,892

This dropped 1510 articles and 10 publications. Most of them were summaries of videos, photo galaries, or did not containe the actual article in the scraped text.

In [472]:
too_short = full_story_df[full_story_df['word_count']<=150]
full_story_df = full_story_df.drop(too_short.index)

In [473]:
len(too_short)

1510

In [474]:
len(full_story_df)

12724

In [475]:
full_story_df['source'].nunique()

840

In [476]:
full_story_df[1234:1240]

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,...,full_text,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin,word_count
1559,The Hitchcock Project for Visualizing Science,New wildlife documentary spotlights Colorado R...,https://hitchcockproject.org/new-wildlife-docu...,2026-02-12T21:18:13+00:00,2026-03-19T02:33:34.063396+00:00,Shows | Ravine | Irvines | Parks | Claytons,colorado | wildlife | documentary | spotlights...,neutral,-0.0256,ok,...,A new documentary showcasing the Colorado Rive...,the-hitchcock-project-for-visualizing-science,University of Nevada-Reno,1.0,35.0,publication_corpora/the-hitchcock-project-for-...,Reno,7.0,0.0,443
1560,The Hitchcock Project for Visualizing Science,What is Chronic Kidney Disease?,https://hitchcockproject.org/what-is-chronic-k...,2026-02-09T22:40:44+00:00,2026-03-19T02:33:34.063396+00:00,Unclassified,chronic | kidney | disease | affects | seven,neutral,0.0,ok,...,Chronic kidney disease affects more than one i...,the-hitchcock-project-for-visualizing-science,University of Nevada-Reno,1.0,35.0,publication_corpora/the-hitchcock-project-for-...,Reno,7.0,0.0,156
1561,The Hitchcock Project for Visualizing Science,"Extremely warm winter days on the rise, new re...",https://hitchcockproject.org/extremely-warm-wi...,2026-02-07T02:33:00+00:00,2026-03-19T02:33:34.063396+00:00,Shelters | Aid | Residents | Dc | Utah,report | extremely | warm | winter | days,neutral,0.0,ok,...,This story was shared with permission from KUN...,the-hitchcock-project-for-visualizing-science,University of Nevada-Reno,1.0,35.0,publication_corpora/the-hitchcock-project-for-...,Reno,7.0,0.0,295
1562,The Hitchcock Project for Visualizing Science,Cognitive Reserve: The Key to a Resilient Mind,https://hitchcockproject.org/cognitive-reserve...,2026-02-06T22:39:24+00:00,2026-03-19T02:33:34.063396+00:00,Services | Wisconsinmadison | Treatment | Prom...,cognitive | reserve | mind | resilient | refers,neutral,0.0294,ok,...,How can you keep your brain agile as you age a...,the-hitchcock-project-for-visualizing-science,University of Nevada-Reno,1.0,35.0,publication_corpora/the-hitchcock-project-for-...,Reno,7.0,0.0,166
1563,The Northerner,Series: The effects of House Bill 4,https://www.thenortherner.com/news/2026/03/18/...,2026-03-19T01:30:45+00:00,2026-03-19T02:33:34.063396+00:00,Unclassified,series | effects | house | bill,neutral,0.0,ok,...,"Kentucky House Bill 4, passed in March 2025, d...",the-northerner,Northern Kentucky University,0.0,52.0,publication_corpora/the-northerner.txt,Highland Heights,1.0,1.0,2057
1564,The Northerner,Freshman star Maddie Moody plans to enter the ...,https://www.thenortherner.com/sports/2026/03/1...,2026-03-18T21:48:33+00:00,2026-03-19T02:33:34.063396+00:00,Unclassified,moody | freshman | maddie | plans | enter,neutral,0.0,ok,...,NKU women’s basketball forward Maddie Moody pl...,the-northerner,Northern Kentucky University,0.0,52.0,publication_corpora/the-northerner.txt,Highland Heights,1.0,1.0,309

Drop articles with over 150 words, but do not containe content (these were found durring preliminary topic labeling). We did not drop podcasts, even though they contained many issues, because some articles containg the word podcast in the title contained real content.

In [495]:
#The Daily Iowan newscast all start this way
#many are >150 words, but do not containe the content of the video
for i, row in full_story_df.iterrows():
    if 'DITV' in full_story_df.loc[i,'title']:
        full_story_df = full_story_df.drop(i)

#The Western Carolina Journalist podcasts stary with Whee
for i, row in full_story_df.iterrows():
    if 'Whee ' in full_story_df.loc[i,'title']:
        full_story_df = full_story_df.drop(i)

#any stories that are croswords
for i, row in full_story_df.iterrows():
    if 'crossword' in full_story_df.loc[i,'title'].lower():
        full_story_df = full_story_df.drop(i)

#these are all one photo of Baseball, but other words from the website got scraped
for i, row in full_story_df.iterrows():
    if 'BSB' in full_story_df.loc[i,'title']:
        full_story_df = full_story_df.drop(i)

#This is not an exhaistive list, but should cover the majority of articles >150 words w/o content

In [497]:
#droped 22 more articles
len(full_story_df)

12702

#### Publications that were dropped due to length of stories

In [498]:
og_pub_list = story_ind['source'].unique()

In [499]:
for i in range(0,len(og_pub_list)):
    if og_pub_list[i] not in full_story_df['source'].unique():
        print(og_pub_list[i])

Point Park News Service
CommunityWire.Miami
New York City News Service
UO Catalyst Journalism Project
Voice of OC
The Seattle Medium
Capitol News Illinois
Fresh Take Georgia
NJ STATE HOUSE NEWS SERVICE

Florida Atlantic U. News
DU Media
USC Annenberg
The Arrow Latest News
The Dominion Post
Tampa Free Press
Patch Labs
Reveille
QCity Metro Latest News
Nebraska News Service
West Texas Tribune
The Daily Gazette
DigitalCommons@Lesley
The Beacon Today
Digital Commons @ Andrews University
Page not found – The Rattler Online
The Record-GC
The Nittany Pride
Earlham Word
The Southeastern
The Wayne Stater
Lesley College Current
The Globe GGC
Mako News
The Mossy Log
ALCIVIA
Mercyhurst
The Herald Times
The Hornet Newspaper
DigitalCommons@CSP
The Bison
BethelClarion.Com
BCO Digital Report
The Critograph
HSU Oracle - Marketing IA
The Horizon-WC

### Add the missing ND info

In [500]:
#the institutions that did not have listings
full_story_df[full_story_df['NewsOutlets2023'].isna()]['institution'].unique()

array(['Multi'], dtype=object)

For university's with multiple campuses where it is unclear where the paper is from, I took the minimum of both NewsOutlets2023 and AdjCountyMin. For colleges not in the Schools 2023 dataset, I found the county they are located in, the counties surrounding it, and the number of news sources useing the Medill 2024 news desert report (). News partnership status was assigned based on location and publication, so non are missing.

Institution, NewsOutlets2023, AdjCountyMin

University of Maryland: 3, 0

University of South Carolina: 0, 0

Arizona State University: 35, 1

University of Oklahoma: 4, 1

Louisiana State University: 1, 0

Vermont State University - Lyndon: 2, 0

Vermont state University-Johnson: 2, 2

University of Texas at Austin: 18, 2

University of Hawaii: 2, 0

University of Pittsburgh: 1, 1

Kent State University: 1, 0

University of Missouri: 7, 1

Rowan University, Atlantic Cape Community College: 2, 1

Texas A&M University: 1, 0 

Ohio State University: 1, 0

University of Michigan: 7, 1

Wesley College: 6, 5

Manhattan University: 3, 23

Pennsylvania State University: 1, 0

The Claremont Colleges: 104, 9

Westminster University: 10, 1

Indiana Wesleyan University: 3, 1

University of Notre Dame, Saint Mary's College, Holy Cross College: 1, 1

Saint Louis Community College-Forest Park: 3, 9

Saint Joseph’s University: 30, 5

Mercy University: 30, 3

New Mexico State University: 1, 0

The University of Tennessee: 2, 0

Colorado State University: 2, 1

William Jewel College: 4, 1

Dallas College-Eastfield: 26, 2

Dallas College-North Lake: 26, 2

Dallas College-Richland: 26, 2

Dallas College-Brookhaven: 26, 2

Miami University: 2, 0

Indiana University Southeast: 0, 1

University of Akron: 3, 0

Southern Illinois University: 3, 0

College of Saint Benedict, Saint Johns University: 10, 1

University of Nevada: 7, 0

University of Wisconsin: 1, 0

These schools are in the School 2023 dataset, but under slightly different names.

University of Colorado Denver: 6, 1

Houston City College: 33, 1

North Carolina State University: 9, 1

These are in the Schools 2023 dataset, but have missing information

Pennsylvania State University-Main Campus: 5

Pennsylvania State University-Penn State Erie-Behrend College: 3

In [501]:
full_story_df[full_story_df['institution']=="Multi"]['source'].unique()

array(['CT Community News', 'Amplify Utah - The Story Room'], dtype=object)

Multi - This has 2 publications that cover whole states

Here they are both news partnerships. I also did not add a value for the county it is in as that does not exists. Fr the adjacent county, i took the min outlents for the whole state/area.

CT Community News - Connecticut: NA, 1

Amplify Utah - The Story Room: NA, 0

In [502]:
for i, row in full_story_df[full_story_df['NewsOutlets2023'].isna()].iterrows():
    
    if full_story_df.loc[i,'institution'] == 'University of South Carolina':
        full_story_df.loc[i,'NewsOutlets2023'] = 0
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'Arizona State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 35
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'University of Oklahoma':
        full_story_df.loc[i,'NewsOutlets2023'] = 4
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Louisiana State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'Vermont State University - Lyndon':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 0

    elif full_story_df.loc[i,'institution'] == 'Vermont state University-Johnson':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_story_df.loc[i,'institution'] == 'University of Texas at Austin':
        full_story_df.loc[i,'NewsOutlets2023'] = 18
        full_story_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_story_df.loc[i,'institution'] == 'University of Hawaii':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'University of Pittsburgh':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Kent State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'University of Missouri':
        full_story_df.loc[i,'NewsOutlets2023'] = 7
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Rowan University, Atlantic Cape Community College':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Texas A&M University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'Ohio State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'University of Michigan':
        full_story_df.loc[i,'NewsOutlets2023'] = 7
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Wesley College':
        full_story_df.loc[i,'NewsOutlets2023'] = 6
        full_story_df.loc[i,'AdjCountyMin'] = 5

    elif full_story_df.loc[i,'institution'] == 'Manhattan University':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
        full_story_df.loc[i,'AdjCountyMin'] = 23

    elif full_story_df.loc[i,'institution'] == 'Pennsylvania State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0

    elif full_story_df.loc[i,'institution'] == 'The Claremont Colleges':
        full_story_df.loc[i,'NewsOutlets2023'] = 104
        full_story_df.loc[i,'AdjCountyMin'] = 9
    
    elif full_story_df.loc[i,'institution'] == 'Westminster University':
        full_story_df.loc[i,'NewsOutlets2023'] = 10
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Indiana Wesleyan University':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
        full_story_df.loc[i,'AdjCountyMin'] = 1

    elif full_story_df.loc[i,'institution'] == "University of Notre Dame, Saint Mary's College, Holy Cross College":
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Saint Louis Community College-Forest Park':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
        full_story_df.loc[i,'AdjCountyMin'] = 9

    elif full_story_df.loc[i,'institution'] == "Saint Joseph’s University":
        full_story_df.loc[i,'NewsOutlets2023'] = 30
        full_story_df.loc[i,'AdjCountyMin'] = 5

    elif full_story_df.loc[i,'institution'] == 'Mercy University':
        full_story_df.loc[i,'NewsOutlets2023'] = 30
        full_story_df.loc[i,'AdjCountyMin'] = 3
        
    elif full_story_df.loc[i,'institution'] == 'New Mexico State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'The University of Tennessee':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'Colorado State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 1

    elif full_story_df.loc[i,'institution'] == "William Jewel College":
        full_story_df.loc[i,'NewsOutlets2023'] = 4
        full_story_df.loc[i,'AdjCountyMin'] = 1

    elif full_story_df.loc[i,'institution'] == 'Dallas College-Eastfield':
        full_story_df.loc[i,'NewsOutlets2023'] = 26
        full_story_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_story_df.loc[i,'institution'] == 'Dallas College-North Lake':
        full_story_df.loc[i,'NewsOutlets2023'] = 26
        full_story_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_story_df.loc[i,'institution'] == 'Dallas College-Richland':
        full_story_df.loc[i,'NewsOutlets2023'] = 26
        full_story_df.loc[i,'AdjCountyMin'] = 2

    elif full_story_df.loc[i,'institution'] == 'Dallas College-Brookhaven':
        full_story_df.loc[i,'NewsOutlets2023'] = 26
        full_story_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_story_df.loc[i,'institution'] == 'Miami University':
        full_story_df.loc[i,'NewsOutlets2023'] = 2
        full_story_df.loc[i,'AdjCountyMin'] = 0
        
    elif full_story_df.loc[i,'institution'] == 'Indiana University Southeast':
        full_story_df.loc[i,'NewsOutlets2023'] = 0
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'University of Akron':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'Southern Illinois University':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
        full_story_df.loc[i,'AdjCountyMin'] = 0

    elif full_story_df.loc[i,'institution'] == "College of Saint Benedict, Saint Johns University":
        full_story_df.loc[i,'NewsOutlets2023'] = 10
        full_story_df.loc[i,'AdjCountyMin'] = 1

    elif full_story_df.loc[i,'institution'] == 'University of Nevada':
        full_story_df.loc[i,'NewsOutlets2023'] = 7
        full_story_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_story_df.loc[i,'institution'] == 'University of Wisconsin':
        full_story_df.loc[i,'NewsOutlets2023'] = 1
        full_story_df.loc[i,'AdjCountyMin'] = 0
        
    elif full_story_df.loc[i,'institution'] == 'University of Colorado Denver':
        full_story_df.loc[i,'NewsOutlets2023'] = 6
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'Houston City College':
        full_story_df.loc[i,'NewsOutlets2023'] = 33
        full_story_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_story_df.loc[i,'institution'] == 'North Carolina State University':
        full_story_df.loc[i,'NewsOutlets2023'] = 9
        full_story_df.loc[i,'AdjCountyMin'] = 1

    #These two are missing the number of news sources in their county, but not in the adjacent one.
    elif full_story_df.loc[i,'institution'] == "Pennsylvania State University-Main Campus":
        full_story_df.loc[i,'NewsOutlets2023'] = 5

    elif full_story_df.loc[i,'institution'] == 'Pennsylvania State University-Penn State Erie-Behrend College':
        full_story_df.loc[i,'NewsOutlets2023'] = 3
    
    else:
        pass

for i, row in full_story_df[full_story_df['institution']=="Multi"].iterrows():
        if full_story_df.loc[i,'source'] == 'Amplify Utah - The Story Room':
            full_story_df.loc[i,'NewsOutlets2023'] = np.nan
            full_story_df.loc[i,'AdjCountyMin'] = 0
        
        elif full_story_df.loc[i,'source'] == 'CT Community News':
            full_story_df.loc[i,'NewsOutlets2023'] = np.nan
            full_story_df.loc[i,'AdjCountyMin'] = 1
        
        else:
            pass

In [503]:
for i, row in full_pub_df[full_pub_df['NewsOutlets2023'].isna()].iterrows():
    if full_pub_df.loc[i,'institution'] == 'University of South Carolina':
        full_pub_df.loc[i,'NewsOutlets2023'] = 0
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Arizona State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 35
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'University of Oklahoma':
        full_pub_df.loc[i,'NewsOutlets2023'] = 4
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Louisiana State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Vermont State University - Lyndon':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Vermont state University-Johnson':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_pub_df.loc[i,'institution'] == 'University of Texas at Austin':
        full_pub_df.loc[i,'NewsOutlets2023'] = 18
        full_pub_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_pub_df.loc[i,'institution'] == 'University of Hawaii':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'University of Pittsburgh':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Kent State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'University of Missouri':
        full_pub_df.loc[i,'NewsOutlets2023'] = 7
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Rowan University, Atlantic Cape Community College':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Texas A&M University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Ohio State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'University of Michigan':
        full_pub_df.loc[i,'NewsOutlets2023'] = 7
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Wesley College':
        full_pub_df.loc[i,'NewsOutlets2023'] = 6
        full_pub_df.loc[i,'AdjCountyMin'] = 5

    elif full_pub_df.loc[i,'institution'] == 'Manhattan University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
        full_pub_df.loc[i,'AdjCountyMin'] = 23

    elif full_pub_df.loc[i,'institution'] == 'Pennsylvania State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0

    elif full_pub_df.loc[i,'institution'] == 'The Claremont Colleges':
        full_pub_df.loc[i,'NewsOutlets2023'] = 104
        full_pub_df.loc[i,'AdjCountyMin'] = 9
    
    elif full_pub_df.loc[i,'institution'] == 'Westminster University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 10
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Indiana Wesleyan University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
        full_pub_df.loc[i,'AdjCountyMin'] = 1

    elif full_pub_df.loc[i,'institution'] == "University of Notre Dame, Saint Mary's College, Holy Cross College":
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Saint Louis Community College-Forest Park':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
        full_pub_df.loc[i,'AdjCountyMin'] = 9

    elif full_pub_df.loc[i,'institution'] == "Saint Joseph’s University":
        full_pub_df.loc[i,'NewsOutlets2023'] = 30
        full_pub_df.loc[i,'AdjCountyMin'] = 5

    elif full_pub_df.loc[i,'institution'] == 'Mercy University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 30
        full_pub_df.loc[i,'AdjCountyMin'] = 3
        
    elif full_pub_df.loc[i,'institution'] == 'New Mexico State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'The University of Tennessee':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Colorado State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 1

    elif full_pub_df.loc[i,'institution'] == "William Jewel College":
        full_pub_df.loc[i,'NewsOutlets2023'] = 4
        full_pub_df.loc[i,'AdjCountyMin'] = 1

    elif full_pub_df.loc[i,'institution'] == 'Dallas College-Eastfield':
        full_pub_df.loc[i,'NewsOutlets2023'] = 26
        full_pub_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_pub_df.loc[i,'institution'] == 'Dallas College-North Lake':
        full_pub_df.loc[i,'NewsOutlets2023'] = 26
        full_pub_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_pub_df.loc[i,'institution'] == 'Dallas College-Richland':
        full_pub_df.loc[i,'NewsOutlets2023'] = 26
        full_pub_df.loc[i,'AdjCountyMin'] = 2

    elif full_pub_df.loc[i,'institution'] == 'Dallas College-Brookhaven':
        full_pub_df.loc[i,'NewsOutlets2023'] = 26
        full_pub_df.loc[i,'AdjCountyMin'] = 2
    
    elif full_pub_df.loc[i,'institution'] == 'Miami University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 0
        
    elif full_pub_df.loc[i,'institution'] == 'Indiana University Southeast':
        full_pub_df.loc[i,'NewsOutlets2023'] = 0
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'University of Akron':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'Southern Illinois University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
        full_pub_df.loc[i,'AdjCountyMin'] = 0

    elif full_pub_df.loc[i,'institution'] == "College of Saint Benedict, Saint Johns University":
        full_pub_df.loc[i,'NewsOutlets2023'] = 10
        full_pub_df.loc[i,'AdjCountyMin'] = 1

    elif full_pub_df.loc[i,'institution'] == 'University of Nevada':
        full_pub_df.loc[i,'NewsOutlets2023'] = 7
        full_pub_df.loc[i,'AdjCountyMin'] = 0
    
    elif full_pub_df.loc[i,'institution'] == 'University of Wisconsin':
        full_pub_df.loc[i,'NewsOutlets2023'] = 1
        full_pub_df.loc[i,'AdjCountyMin'] = 0
        
    elif full_pub_df.loc[i,'institution'] == 'University of Colorado Denver':
        full_pub_df.loc[i,'NewsOutlets2023'] = 6
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'Houston City College':
        full_pub_df.loc[i,'NewsOutlets2023'] = 33
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    elif full_pub_df.loc[i,'institution'] == 'North Carolina State University':
        full_pub_df.loc[i,'NewsOutlets2023'] = 9
        full_pub_df.loc[i,'AdjCountyMin'] = 1

    #These two are missing the number of news sources in their county, but not in the adjacent one.
    elif full_pub_df.loc[i,'institution'] == "Pennsylvania State University-Main Campus":
        full_pub_df.loc[i,'NewsOutlets2023'] = 5

    elif full_pub_df.loc[i,'institution'] == 'Pennsylvania State University-Penn State Erie-Behrend College':
        full_pub_df.loc[i,'NewsOutlets2023'] = 3
    
    #These two were not in the full_story_df, but are in the full_pub_df
    elif full_pub_df.loc[i,'institution'] == 'Vermont State University - Castleton':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 2

    elif full_pub_df.loc[i,'institution'] == 'Commonwealth University of Pennsylvania-Lock Haven':
        full_pub_df.loc[i,'NewsOutlets2023'] = 2
        full_pub_df.loc[i,'AdjCountyMin'] = 1
    
    else:
        pass

for i, row in full_pub_df[full_pub_df['institution']=="Multi"].iterrows():
        if full_pub_df.loc[i,'source'] == 'Amplify Utah - The Story Room':
            full_pub_df.loc[i,'NewsOutlets2023'] = np.nan
            full_pub_df.loc[i,'AdjCountyMin'] = 0
        
        elif full_pub_df.loc[i,'source'] == 'CT Community News':
            full_pub_df.loc[i,'NewsOutlets2023'] = np.nan
            full_pub_df.loc[i,'AdjCountyMin'] = 1
        
        else:
            pass

In [504]:
full_story_df[full_story_df['AdjCountyMin'].isna()]

Empty DataFrame
Columns: [source, title, link, published, captured_at, theme, keywords, sentiment_label, sentiment_score, extraction_status, full_text_path, full_text, slug, institution, news_partnership, story_count, corpus_file, CITY, NewsOutlets2023, AdjCountyMin, word_count, news_status, Adj_news_status]
Index: []

[0 rows x 23 columns]

In [505]:
#Dropped when articles with <150 words were dropped
full_pub_df[full_pub_df['AdjCountyMin'].isna()]

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin,news_status,Adj_news_status
940,NJ STATE HOUSE NEWS SERVICE,nj-state-house-news-service,Multi,NaN,1,publication_corpora/nj-state-house-news-servic...,NaN,NaN,NaN,0.0,0.0

## Create a limited news access column

In [506]:
#create a limited news area column and an adj limited news area column
#create new column
full_pub_df['news_status'] = np.nan
#add 1 for nd and 0 otherwise
for i, row in full_pub_df.iterrows():
    if full_pub_df.loc[i,'NewsOutlets2023'] <= 1:
        full_pub_df.loc[i,'news_status'] = 1
    else:
        full_pub_df.loc[i,'news_status'] = 0

#create new column
full_pub_df['Adj_news_status'] = np.nan
#add 1 for nd and 0 otherwise
for i, row in full_pub_df.iterrows():
    if full_pub_df.loc[i,'AdjCountyMin'] <= 1:
        full_pub_df.loc[i,'Adj_news_status'] = 1
    else:
        full_pub_df.loc[i,'Adj_news_status'] = 0

In [507]:
full_pub_df.head()

,source,slug,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin,news_status,Adj_news_status
0,The NewsHouse,the-newshouse,Syracuse University,0.0,381,publication_corpora/the-newshouse.txt,Syracuse,6.0,1.0,0.0,1.0
1,The Observer,the-observer,University of Illinois Springfield,0.0,10,publication_corpora/the-observer.txt,Springfield,12.0,1.0,0.0,1.0
2,The Observer-NDSM,the-observer,"University of Notre Dame, Saint Mary's College...",0.0,46,publication_corpora/the-observer.txt,NaN,1.0,1.0,1.0,1.0
3,The Observer-FU,the-observer,Fordham University,0.0,98,publication_corpora/the-observer.txt,Bronx,5.0,5.0,0.0,0.0
4,The Observer-CWU,the-observer,Central Washington University,0.0,10,publication_corpora/the-observer.txt,Ellensburg,2.0,1.0,0.0,1.0

In [508]:
#create a ND/limited news acess column and an adj ND/limited acess column
#create new column
full_story_df['news_status'] = np.nan
#add 1 for nd and 0 otherwise
for i, row in full_story_df.iterrows():
    if full_story_df.loc[i,'NewsOutlets2023'] <= 1:
        full_story_df.loc[i,'news_status'] = 1
    else:
        full_story_df.loc[i,'news_status'] = 0

#create new column
full_story_df['Adj_news_status'] = np.nan
#add 1 for nd and 0 otherwise
for i, row in full_story_df.iterrows():
    if full_story_df.loc[i,'AdjCountyMin'] <= 1:
        full_story_df.loc[i,'Adj_news_status'] = 1
    else:
        full_story_df.loc[i,'Adj_news_status'] = 0

In [509]:
full_story_df.head()

,source,title,link,published,captured_at,theme,keywords,sentiment_label,sentiment_score,extraction_status,...,institution,news_partnership,story_count,corpus_file,CITY,NewsOutlets2023,AdjCountyMin,word_count,news_status,Adj_news_status
25,Crosstown,Building is coming back in the Palisades,https://xtown.la/2025/09/30/building-pacific-p...,"Tue, 30 Sep 2025 20:59:27 +0000",2026-02-03 11:52:48,Unclassified,building | coming | back | palisades,neutral,0.0,ok,...,University of Southern California,1.0,14.0,publication_corpora/crosstown.txt,Los Angeles,104.0,9.0,920,0.0,0.0
26,Crosstown,Sun is setting on new solar power in Los Angeles,https://xtown.la/2025/09/11/solar-power-los-an...,"Fri, 12 Sep 2025 02:08:41 +0000",2026-02-03 11:52:48,Conference | Collegiate | Transition | Initiat...,setting | solar | power | angeles,neutral,0.0,ok,...,University of Southern California,1.0,14.0,publication_corpora/crosstown.txt,Los Angeles,104.0,9.0,1298,0.0,0.0
27,Crosstown,Crime in Los Angeles in four charts,https://xtown.la/2025/08/25/crime-in-los-angel...,"Mon, 25 Aug 2025 15:30:11 +0000",2026-02-03 11:52:48,Unclassified,crime | angeles | four | charts,neutral,0.0,ok,...,University of Southern California,1.0,14.0,publication_corpora/crosstown.txt,Los Angeles,104.0,9.0,669,0.0,0.0
28,Crosstown,Los Angeles’s pool party may be coming to a close,https://xtown.la/2025/08/18/pool-permits-los-a...,"Mon, 18 Aug 2025 13:00:06 +0000",2026-02-03 11:52:48,Unclassified,angeles | pool | party | coming | close,neutral,0.0,ok,...,University of Southern California,1.0,14.0,publication_corpora/crosstown.txt,Los Angeles,104.0,9.0,406,0.0,0.0
29,Crosstown,Your streetlight went dark. Could a new tariff...,https://xtown.la/2025/08/06/copper-wire-tarrif...,"Wed, 06 Aug 2025 17:01:45 +0000",2026-02-03 11:52:48,Unclassified,streetlight | went | dark | could | tariff,neutral,0.0,ok,...,University of Southern California,1.0,14.0,publication_corpora/crosstown.txt,Los Angeles,104.0,9.0,735,0.0,0.0

## Save the dataframes as a csv file for future use

In [510]:
full_story_df.to_csv('news_df.csv', index=False)

In [511]:
full_pub_df.to_csv('pub_df.csv', index=False)